CREATE TABLE terminals (
	terminalID int NOT NULL AUTO_INCREMENT,
	n_terminal int NULL,
	name_terminal varchar(30) NULL,
	email_terminal varchar(30) NULL,
	fio1 varchar(50) NULL,
	fio2 varchar(50) NULL,
	adr1 varchar(50) NULL,
	adr2 varchar(50) NULL,
	phone1 varchar(50) NULL,
	phone2 varchar(50) NULL,
	region varchar(30) NULL,
	volume int NULL,
	PRIMARY KEY(terminalID)
);

CREATE TABLE pacients (
	pacientID bigint NOT NULL AUTO_INCREMENT,
	n_terminal int NULL,
	n_kart int NULL,
	family varchar(30) NULL,
	name varchar(20) NULL,
	surname varchar(30) NULL,
	burthday datetime NULL,
	sex varchar(3) NULL,
	rost int(11) NULL,
	ves int(11) NULL,
	bedro int(11) NULL,
	talia int(11) NULL,
	coment varchar(8000) NULL,
	policy_series varchar(5) NULL,
	policy_number varchar(8) NULL,
	location varchar(5) NULL,
	marital_status varchar(7) NULL,
	social_status tinyint NULL,
	registration_date datetime NULL,
	last_examination_date datetime NULL,
	next_examination_date datetime NULL,
	death_date datetime NULL,
	death_diagnosis varchar(150) NULL,
	death_diagnosis_mkb10 varchar(10) NULL,
	close_date datetime NULL,
	close_reason tinyint NULL,
	city varchar(30) NULL,
	street varchar(50) NULL,
	house_number int NULL,
	house_korpus varchar(3) NULL,
	house_unit_number int NULL,
	house_phone varchar(20) NULL,
	business_phone varchar(20) NULL,
	education varchar(50) NULL,
	profession varchar(50) NULL,
	employment varchar(100) NULL,
	post varchar(50) NULL,
	diagnosis varchar(150) NULL,
	diagnosis_mkb10 varchar(10) NULL,
	dispensary_group varchar(50) NULL,
	_add int NULL,
	ads int NULL,
	stepen_ag int NULL,
	stepen_riska int NULL,
	f_riska varchar(10) NULL,
	por_org_mish varchar(10) NULL,
	soput_zab varchar(10) NULL,
	sah_diabet varchar(1) NULL,
	conclusion int NULL,
	diag_mkb10_2 varchar(10) NULL,
	diag_mkb10_3 varchar(10) NULL,
	diag_mkb10_4 varchar(10) NULL,
	diag_mkb10_5 varchar(10) NULL,
	last_mail_sending_date datetime NULL,
	last_mail_loaded_date datetime NULL,
	date_opening datetime NULL,
	PRIMARY KEY(pacientID)
);


CREATE TABLE pac_meas (
	pac_measID bigint NOT NULL AUTO_INCREMENT,
	n_terminal int NULL,
	n_kart int NULL,
	n_meas tinyint NULL,
	n_sourcer varchar(10) NULL,
	m_date datetime NULL,
	m_time varchar(5) NULL,
	dd_corr tinyint NULL,
	coment varchar(8000) NULL,
	mangeta varchar(2) NULL,
	tst_izm_do varchar(64) NULL,
	tst_izm_pos varchar(64) NULL,
	drag1 int NULL,
	drag2 int NULL,
	drag3 int NULL,
	drag4 int NULL,
	drag5 int NULL,
	drag6 int NULL,
	drag1_doza varchar(30) NULL,
	drag2_doza varchar(30) NULL,
	drag3_doza varchar(30) NULL,
	drag4_doza varchar(30) NULL,
	drag5_doza varchar(30) NULL,
	drag6_doza varchar(30) NULL,
	drag1_time varchar(30) NULL,
	drag2_time varchar(30) NULL,
	drag3_time varchar(30) NULL,
	drag4_time varchar(30) NULL,
	drag5_time varchar(30) NULL,
	drag6_time varchar(30) NULL,
	no_drag_days int NULL,
	meas_cond int NULL,
	mon_nar_son int NULL,
	kach_sna int NULL,
	proch_simpt varchar(30) NULL,
	time_dream varchar(12) NULL,
	time_eat varchar(18) NULL,
	ves int NULL,
	rost int NULL,
	talia int NULL,
	bedro int NULL,
	_add int NULL,
	ads int NULL,
	puls int NULL,
	galoba varchar(10) NULL,
	dr_galoba varchar(30) NULL,
	f_riska varchar(10) NULL,
	sah_diabet varchar(1) NULL,
	por_org_mish varchar(10) NULL,
	soput_zab varchar(10) NULL,
	diagnosis_mkb10 varchar(10) NULL,
	diagnosis varchar(8000) NULL,
	conclusion int NULL,
	stepen_ag int NULL,
	stepen_riska int NULL,
	diag_mkb10_2 varchar(10) NULL,
	diag_mkb10_3 varchar(10) NULL,
	diag_mkb10_4 varchar(10) NULL,
	diag_mkb10_5 varchar(10) NULL,
	date_loaded datetime NULL,
	date_sending datetime NULL,
	file_name_data varchar(200) NULL,
	type_meas varchar(10) NULL,
	PRIMARY KEY(pac_measID)
);


CREATE TABLE meas (
	measID bigint NOT NULL AUTO_INCREMENT,
	n_terminal int NULL,
	n_kart int NULL,
	n_meas int NULL,
	p_off int NULL,
	p_sp int NULL,
	p_dp int NULL,
	p_fp int NULL,
	p_fl_a varchar(1) NULL,
	p_fl_m varchar(1) NULL,
	p_date datetime NULL,
	p_time varchar(5) NULL,
	p_fl_err varchar(1) NULL,
	p_fl_rst varchar(1) NULL,
	p_fl_evnt varchar(1) NULL,
	p_fl_sevnt varchar(1) NULL,
	p_fl varchar(20) NULL,
	PRIMARY KEY(measID)
);

