(function () {

	var $ = require("utils");

	var Loc = new $.Class({

		initialize: function(lang) {
			var n = lang == "ru" ? 0 : 1;
			for (var k in this.data) {
				this[k] = this.data[k][n];
			}
		},

		data: {
			ABP: ["Артериальное давление", "Arterial blood pressure"],
			sys_abp: ["САД", "Upper"],
			dia_abp: ["ДАД", "Lower"],
			pulse_abp: ["ПАД", "Diff"],
			rate: ["ЧСС", "Rate"],
			rate2: ["Частота пульса", "Heart rate"],
			time: ["Время", "Time"],
			error: ["Ошибка", "Err"],
			error2: ["Ошибка", "Error"],
			main: ["Главная", "Main"],
			admin: ["Администратор", "Administrator"],
			terminal: ["Терминал ", "Terminal "],
			add_card: ["Добавить карточку", "Add new card"],
			card_info: ["Пациент", "Patient"],
			card_history: ["Карточка", "Card"],
			diagnosis: ["Диагноз", "Diagnosis"],
			monitoring: ["Мониторирование", "Monitoring"],
			new_monitoring: ["Новое мониторирование", "New monitoring"],
			new_meas: ["Новое измерение", "New measurement"],
			analysis: ["Анализ", "Analysis"],
			conditions: ["Условия мониторирования", "Monitoring conditions"],
			comment: ["Комментарий", "Comment"],
			conclusion: ["Заключение", "Conclusion"],
			measurement: ["Измерение", "Measurement"],
			sys_abp2: ["Систолическое АД", "Systolic ABP"],
			dia_abp2: ["Диастолическое АД", "Diastolic ABP"],
			sys_abp3: ["Систолическое артериальное давление", "Systolic arterial blood pressure"],
			dia_abp3: ["Диастолическое артериальное давление", "Diastolic arterial blood pressure"],
			pulse_bp: ["Пульсовое АД", "Pulse ABP"],
			pulse_bp2: ["Пульсовое АД = САД - ДАД", null],
			kerdo: ["Индекс Кердо", "Kerdo index"],
			kerdo2: ["Вегетативный индекс Кердо (ВИ) = (1 - ДАД / ЧСС) * 100", null],
			criterion_s: ["Критерий S", "Criterion S"],
			criterion_s2: ["Критерий S = (САД * ДАД) / (САД - ДАД)", null],
			double_product: ["Двойное произведение", "Double product"],
			double_product2: ["Двойное произведение = (САД * ЧСС) / 100", null],
			minimum: ["Минимум", "Minimum"],
			maximum: ["Максимум", "Maximum"],
			average: ["Среднее", "Average"],
			stdev: ["Стандартное отклонение", "Standard deviation"],
			surname: ["Фамилия", "Surname"],
			name: ["Имя", "Name"],
			second_name: ["Отчество", "Second name"],
			dob: ["Дата рождения(дд.мм.гггг)", "Date of birth(dd.mm.yyyy)"],
			dob2: ["Дата рождения", "Date of birth"],
			sex: ["Пол", "Sex"],
			height: ["Рост", "Height"],
			weight: ["Вес", "Weight"],
			soc_category: ["Социальная категория", "Social category"],
			marital_status: ["Семейное положение", "Marital status"],
			education: ["Образование", "Education"],
			company: ["Место работы", "Company"],
			profession: ["Профессия", "Profession"],
			position: ["Должность", "Position"],
			city: ["Город", "City"],
			street: ["Улица", "Street"],
			phone1: ["Домашний телефон", "Home phone"],
			phone2: ["Служебный телефон", "Work phone"],
			male: ["мужской", "male"],
			female: ["женский", "female"],
			married: ["женат / замужем", "married"],
			single: ["не женат / не замужем", "single"],
			hip: ["Окружность бедер", "Hip"],
			waist: ["Окружность талии", "Waist"],
			house: ["Дом", "House"],
			building: ["Корпус", "Building"],
			appart: ["Квартира", "Appart"],
			policy_series: ["Серия полиса", "Policy series"],
			policy_number: ["Номер полиса", "Policy number"],
			dispensary_group: ["Группа диспансерного учета", "Dispensary group"],
			card_created: ["Карточка создана", "Card has been created"],
			card_changed: ["Карточка изменена", "Card has been modified"],
			card_create_error: ["Ошибка при создании карточки", "Card create error"],
			save: ["Сохранить", "Save"],
			add: ["Добавить", "Add"],
			read_confirm: ["Нажмите кнопку 'Событие'. Продолжить чтение данных?", "Press 'status' button. Continue downloading data?"],
			prog_confirm: ["Нажмите кнопку 'Событие'. Продолжить программирование?", "Press 'status' button. Continue programming?"],
			read_complete: ["Загрузка данных завершена", "Data download complete"],
			read_error1: ["Ошибка записи данных", "Data download error"],
			read_error2: ["Ошибка чтения данных", "Data read error"],
			prog_error: ["Ошибка при программировании монитора!", "Programming error"],
			prog_success: ["Программирование завершено", "Programming complete"],
			low_risk: ["низкий риск", "low risk"],
			average_risk: ["средний риск", "average risk"],
			high_risk: ["высокий риск", "high risk"],
			very_high_risk: ["очень высокий риск", "very high risk"],
			risk_lt15: ["менее 15%", "less than 15%"],
			risk_15_20: ["15-20%", "15-20%"],
			risk_20_30: ["20-30%", "20-30%"],
			risk_gt30: ["30% или выше", "greater than 30%"],
			added: ["Проведено ", "Added "],
			SMAD: ["суточное мониторирование СМАД #", "daily monitoring #"],
			card_conclusion: ["Заключение по суточному мониторированию СМАД #", "Daily monitoring conclusion #"],
			report: ["Отчет", "Report"],
			daily_index: ["Суточный индекс", "Daily index"],
			morning_speed: ["Скорость утреннего повышения", "Morning increase"],
			hypertension: ["гиперт.", "Hypertension"],
			hypotension: ["гипот.", "Hypotension"],
			pressure_load: ["Индекс времени", "Pressure load"],
			area_under_curve: ["Индекс площади", "Area under curve"],
			active_period: ["Активный период", "Active period"],
			passive_period: ["Пассивный период", "Passive period"],
			full_period: ["Весь период", "Full period"],
			number: ["№", "#"],
			card_number: ["№ карточки", "Card #"],
			patient: ["Пациент", "Patient"],
			gender: ["Пол", "Gender"],
			age: ["Возраст", "Age"],
			meas_date: ["Дата мониторирования", "Monitoring date"],
			weight_index: ["Индекс массы тела", "Weight index"],
			hip_waist_index: ["Индекс \"талия-бедро\"", "Hip-waist index"],
			send: ["Отправить на рассмотрение", "Send on review"],
			send_confirm: ["Отправить мониторирование на рассмотрение?", "Send measurement on review?"],
			mark_reviewed: ["Завершить анализ", "Finish review"],
			confirm_reviewed: ["Завершить анализ мониторирования?", "Finish monitoring review?"],
			new_measurements: ["Новые измерения:", "New measurements:"],
			reviewed_measurements: ["Рассмотренные измерения:", "Reviewed measurements:"],
			events: ["События", "Events"],
		}

	});

	exports.Loc = Loc;

})();
